/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BeginnersRouteImport } from './routes/beginners'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FinalTestRouteImport } from './routes/final-test'
import { Route as LevelsRouteImport } from './routes/levels'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TeamRouteImport } from './routes/team'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as LectureLectureIdRouteImport } from './routes/lecture.$lectureId'
import { Route as LevelSlugRouteImport } from './routes/level.$slug'
import { Route as SeriesSeriesIdRouteImport } from './routes/series.$seriesId'
import { Route as SessionCodeRouteImport } from './routes/session.$code'
import { Route as TestTokenRouteImport } from './routes/test.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeginnersRoute = BeginnersRouteImport.update({
  id: '/beginners',
  path: '/beginners',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FinalTestRoute = FinalTestRouteImport.update({
  id: '/final-test',
  path: '/final-test',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelsRoute = LevelsRouteImport.update({
  id: '/levels',
  path: '/levels',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LectureLectureIdRoute = LectureLectureIdRouteImport.update({
  id: '/lecture/$lectureId',
  path: '/lecture/$lectureId',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelSlugRoute = LevelSlugRouteImport.update({
  id: '/level/$slug',
  path: '/level/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSeriesIdRoute = SeriesSeriesIdRouteImport.update({
  id: '/series/$seriesId',
  path: '/series/$seriesId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionCodeRoute = SessionCodeRouteImport.update({
  id: '/session/$code',
  path: '/session/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const TestTokenRoute = TestTokenRouteImport.update({
  id: '/test/$token',
  path: '/test/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beginners': typeof BeginnersRoute
  '/dashboard': typeof DashboardRoute
  '/final-test': typeof FinalTestRoute
  '/levels': typeof LevelsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reels': typeof ReelsRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/team': typeof TeamRoute
  '/admin/login': typeof AdminLoginRoute
  '/join/$token': typeof JoinTokenRoute
  '/lecture/$lectureId': typeof LectureLectureIdRoute
  '/level/$slug': typeof LevelSlugRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
  '/session/$code': typeof SessionCodeRoute
  '/test/$token': typeof TestTokenRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beginners': typeof BeginnersRoute
  '/dashboard': typeof DashboardRoute
  '/final-test': typeof FinalTestRoute
  '/levels': typeof LevelsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reels': typeof ReelsRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/team': typeof TeamRoute
  '/admin/login': typeof AdminLoginRoute
  '/join/$token': typeof JoinTokenRoute
  '/lecture/$lectureId': typeof LectureLectureIdRoute
  '/level/$slug': typeof LevelSlugRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
  '/session/$code': typeof SessionCodeRoute
  '/test/$token': typeof TestTokenRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beginners': typeof BeginnersRoute
  '/dashboard': typeof DashboardRoute
  '/final-test': typeof FinalTestRoute
  '/levels': typeof LevelsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reels': typeof ReelsRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/team': typeof TeamRoute
  '/admin/login': typeof AdminLoginRoute
  '/join/$token': typeof JoinTokenRoute
  '/lecture/$lectureId': typeof LectureLectureIdRoute
  '/level/$slug': typeof LevelSlugRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
  '/session/$code': typeof SessionCodeRoute
  '/test/$token': typeof TestTokenRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beginners'
    | '/dashboard'
    | '/final-test'
    | '/levels'
    | '/notifications'
    | '/profile'
    | '/reels'
    | '/resources'
    | '/search'
    | '/team'
    | '/admin/login'
    | '/join/$token'
    | '/lecture/$lectureId'
    | '/level/$slug'
    | '/series/$seriesId'
    | '/session/$code'
    | '/test/$token'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beginners'
    | '/dashboard'
    | '/final-test'
    | '/levels'
    | '/notifications'
    | '/profile'
    | '/reels'
    | '/resources'
    | '/search'
    | '/team'
    | '/admin/login'
    | '/join/$token'
    | '/lecture/$lectureId'
    | '/level/$slug'
    | '/series/$seriesId'
    | '/session/$code'
    | '/test/$token'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/beginners'
    | '/dashboard'
    | '/final-test'
    | '/levels'
    | '/notifications'
    | '/profile'
    | '/reels'
    | '/resources'
    | '/search'
    | '/team'
    | '/admin/login'
    | '/join/$token'
    | '/lecture/$lectureId'
    | '/level/$slug'
    | '/series/$seriesId'
    | '/session/$code'
    | '/test/$token'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeginnersRoute: typeof BeginnersRoute
  DashboardRoute: typeof DashboardRoute
  FinalTestRoute: typeof FinalTestRoute
  LevelsRoute: typeof LevelsRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  ReelsRoute: typeof ReelsRoute
  ResourcesRoute: typeof ResourcesRoute
  SearchRoute: typeof SearchRoute
  TeamRoute: typeof TeamRoute
  AdminLoginRoute: typeof AdminLoginRoute
  JoinTokenRoute: typeof JoinTokenRoute
  LectureLectureIdRoute: typeof LectureLectureIdRoute
  LevelSlugRoute: typeof LevelSlugRoute
  SeriesSeriesIdRoute: typeof SeriesSeriesIdRoute
  SessionCodeRoute: typeof SessionCodeRoute
  TestTokenRoute: typeof TestTokenRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beginners': {
      id: '/beginners'
      path: '/beginners'
      fullPath: '/beginners'
      preLoaderRoute: typeof BeginnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/final-test': {
      id: '/final-test'
      path: '/final-test'
      fullPath: '/final-test'
      preLoaderRoute: typeof FinalTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels': {
      id: '/levels'
      path: '/levels'
      fullPath: '/levels'
      preLoaderRoute: typeof LevelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecture/$lectureId': {
      id: '/lecture/$lectureId'
      path: '/lecture/$lectureId'
      fullPath: '/lecture/$lectureId'
      preLoaderRoute: typeof LectureLectureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/level/$slug': {
      id: '/level/$slug'
      path: '/level/$slug'
      fullPath: '/level/$slug'
      preLoaderRoute: typeof LevelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$seriesId': {
      id: '/series/$seriesId'
      path: '/series/$seriesId'
      fullPath: '/series/$seriesId'
      preLoaderRoute: typeof SeriesSeriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$code': {
      id: '/session/$code'
      path: '/session/$code'
      fullPath: '/session/$code'
      preLoaderRoute: typeof SessionCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$token': {
      id: '/test/$token'
      path: '/test/$token'
      fullPath: '/test/$token'
      preLoaderRoute: typeof TestTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeginnersRoute: BeginnersRoute,
  DashboardRoute: DashboardRoute,
  FinalTestRoute: FinalTestRoute,
  LevelsRoute: LevelsRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  ReelsRoute: ReelsRoute,
  ResourcesRoute: ResourcesRoute,
  SearchRoute: SearchRoute,
  TeamRoute: TeamRoute,
  AdminLoginRoute: AdminLoginRoute,
  JoinTokenRoute: JoinTokenRoute,
  LectureLectureIdRoute: LectureLectureIdRoute,
  LevelSlugRoute: LevelSlugRoute,
  SeriesSeriesIdRoute: SeriesSeriesIdRoute,
  SessionCodeRoute: SessionCodeRoute,
  TestTokenRoute: TestTokenRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
