/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantsRouteImport } from './routes/assistants'
import { Route as BeginnersRouteImport } from './routes/beginners'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EnrollmentVideoRouteImport } from './routes/enrollment-video'
import { Route as ExecutiveRouteImport } from './routes/executive'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as LeaveRouteImport } from './routes/leave'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PayMentorshipRouteImport } from './routes/pay-mentorship'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SeatsRouteImport } from './routes/seats'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TodoRouteImport } from './routes/todo'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as TrainingRoomRouteImport } from './routes/training-room'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AiIndexRouteImport } from './routes/ai.index'
import { Route as AiThreadIdRouteImport } from './routes/ai.$threadId'
import { Route as ApiAiRouteImport } from './routes/api.ai'
import { Route as CourseCourseIdRouteImport } from './routes/course.$courseId'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as LectureLectureIdRouteImport } from './routes/lecture.$lectureId'
import { Route as ReportTokenRouteImport } from './routes/report.$token'
import { Route as ResourceResourceIdRouteImport } from './routes/resource.$resourceId'
import { Route as SessionCodeRouteImport } from './routes/session.$code'
import { Route as AdminMemberMemberIdRouteImport } from './routes/admin.member.$memberId'
import { Route as ApiPublicAiRouteImport } from './routes/api.public.ai'
import { Route as ApplyGrowthTokenRouteImport } from './routes/apply.growth.$token'
import { Route as ApiPublicCronNotifyRouteImport } from './routes/api.public.cron.notify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantsRoute = AssistantsRouteImport.update({
  id: '/assistants',
  path: '/assistants',
  getParentRoute: () => rootRouteImport,
} as any)
const BeginnersRoute = BeginnersRouteImport.update({
  id: '/beginners',
  path: '/beginners',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollmentVideoRoute = EnrollmentVideoRouteImport.update({
  id: '/enrollment-video',
  path: '/enrollment-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveRoute = ExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveRoute = LeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PayMentorshipRoute = PayMentorshipRouteImport.update({
  id: '/pay-mentorship',
  path: '/pay-mentorship',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SeatsRoute = SeatsRouteImport.update({
  id: '/seats',
  path: '/seats',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TodoRoute = TodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoomRoute = TrainingRoomRouteImport.update({
  id: '/training-room',
  path: '/training-room',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AiIndexRoute = AiIndexRouteImport.update({
  id: '/ai/',
  path: '/ai/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiThreadIdRoute = AiThreadIdRouteImport.update({
  id: '/ai/$threadId',
  path: '/ai/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRoute = ApiAiRouteImport.update({
  id: '/api/ai',
  path: '/api/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdRoute = CourseCourseIdRouteImport.update({
  id: '/course/$courseId',
  path: '/course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LectureLectureIdRoute = LectureLectureIdRouteImport.update({
  id: '/lecture/$lectureId',
  path: '/lecture/$lectureId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportTokenRoute = ReportTokenRouteImport.update({
  id: '/report/$token',
  path: '/report/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceResourceIdRoute = ResourceResourceIdRouteImport.update({
  id: '/resource/$resourceId',
  path: '/resource/$resourceId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionCodeRoute = SessionCodeRouteImport.update({
  id: '/session/$code',
  path: '/session/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMemberMemberIdRoute = AdminMemberMemberIdRouteImport.update({
  id: '/admin/member/$memberId',
  path: '/admin/member/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiRoute = ApiPublicAiRouteImport.update({
  id: '/api/public/ai',
  path: '/api/public/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyGrowthTokenRoute = ApplyGrowthTokenRouteImport.update({
  id: '/apply/growth/$token',
  path: '/apply/growth/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronNotifyRoute = ApiPublicCronNotifyRouteImport.update({
  id: '/api/public/cron/notify',
  path: '/api/public/cron/notify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistants': typeof AssistantsRoute
  '/beginners': typeof BeginnersRoute
  '/chat': typeof ChatRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/enrollment-video': typeof EnrollmentVideoRoute
  '/executive': typeof ExecutiveRoute
  '/founder': typeof FounderRoute
  '/leave': typeof LeaveRoute
  '/notifications': typeof NotificationsRoute
  '/pay-mentorship': typeof PayMentorshipRoute
  '/profile': typeof ProfileRoute
  '/reels': typeof ReelsRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/seats': typeof SeatsRoute
  '/sessions': typeof SessionsRoute
  '/team': typeof TeamRoute
  '/todo': typeof TodoRoute
  '/training': typeof TrainingRoute
  '/training-room': typeof TrainingRoomRoute
  '/admin/login': typeof AdminLoginRoute
  '/ai/$threadId': typeof AiThreadIdRoute
  '/api/ai': typeof ApiAiRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/join/$token': typeof JoinTokenRoute
  '/lecture/$lectureId': typeof LectureLectureIdRoute
  '/report/$token': typeof ReportTokenRoute
  '/resource/$resourceId': typeof ResourceResourceIdRoute
  '/session/$code': typeof SessionCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/ai/': typeof AiIndexRoute
  '/admin/member/$memberId': typeof AdminMemberMemberIdRoute
  '/api/public/ai': typeof ApiPublicAiRoute
  '/apply/growth/$token': typeof ApplyGrowthTokenRoute
  '/api/public/cron/notify': typeof ApiPublicCronNotifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistants': typeof AssistantsRoute
  '/beginners': typeof BeginnersRoute
  '/chat': typeof ChatRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/enrollment-video': typeof EnrollmentVideoRoute
  '/executive': typeof ExecutiveRoute
  '/founder': typeof FounderRoute
  '/leave': typeof LeaveRoute
  '/notifications': typeof NotificationsRoute
  '/pay-mentorship': typeof PayMentorshipRoute
  '/profile': typeof ProfileRoute
  '/reels': typeof ReelsRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/seats': typeof SeatsRoute
  '/sessions': typeof SessionsRoute
  '/team': typeof TeamRoute
  '/todo': typeof TodoRoute
  '/training': typeof TrainingRoute
  '/training-room': typeof TrainingRoomRoute
  '/admin/login': typeof AdminLoginRoute
  '/ai/$threadId': typeof AiThreadIdRoute
  '/api/ai': typeof ApiAiRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/join/$token': typeof JoinTokenRoute
  '/lecture/$lectureId': typeof LectureLectureIdRoute
  '/report/$token': typeof ReportTokenRoute
  '/resource/$resourceId': typeof ResourceResourceIdRoute
  '/session/$code': typeof SessionCodeRoute
  '/admin': typeof AdminIndexRoute
  '/ai': typeof AiIndexRoute
  '/admin/member/$memberId': typeof AdminMemberMemberIdRoute
  '/api/public/ai': typeof ApiPublicAiRoute
  '/apply/growth/$token': typeof ApplyGrowthTokenRoute
  '/api/public/cron/notify': typeof ApiPublicCronNotifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistants': typeof AssistantsRoute
  '/beginners': typeof BeginnersRoute
  '/chat': typeof ChatRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/enrollment-video': typeof EnrollmentVideoRoute
  '/executive': typeof ExecutiveRoute
  '/founder': typeof FounderRoute
  '/leave': typeof LeaveRoute
  '/notifications': typeof NotificationsRoute
  '/pay-mentorship': typeof PayMentorshipRoute
  '/profile': typeof ProfileRoute
  '/reels': typeof ReelsRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/seats': typeof SeatsRoute
  '/sessions': typeof SessionsRoute
  '/team': typeof TeamRoute
  '/todo': typeof TodoRoute
  '/training': typeof TrainingRoute
  '/training-room': typeof TrainingRoomRoute
  '/admin/login': typeof AdminLoginRoute
  '/ai/$threadId': typeof AiThreadIdRoute
  '/api/ai': typeof ApiAiRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/join/$token': typeof JoinTokenRoute
  '/lecture/$lectureId': typeof LectureLectureIdRoute
  '/report/$token': typeof ReportTokenRoute
  '/resource/$resourceId': typeof ResourceResourceIdRoute
  '/session/$code': typeof SessionCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/ai/': typeof AiIndexRoute
  '/admin/member/$memberId': typeof AdminMemberMemberIdRoute
  '/api/public/ai': typeof ApiPublicAiRoute
  '/apply/growth/$token': typeof ApplyGrowthTokenRoute
  '/api/public/cron/notify': typeof ApiPublicCronNotifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistants'
    | '/beginners'
    | '/chat'
    | '/courses'
    | '/dashboard'
    | '/enrollment-video'
    | '/executive'
    | '/founder'
    | '/leave'
    | '/notifications'
    | '/pay-mentorship'
    | '/profile'
    | '/reels'
    | '/resources'
    | '/search'
    | '/seats'
    | '/sessions'
    | '/team'
    | '/todo'
    | '/training'
    | '/training-room'
    | '/admin/login'
    | '/ai/$threadId'
    | '/api/ai'
    | '/course/$courseId'
    | '/join/$token'
    | '/lecture/$lectureId'
    | '/report/$token'
    | '/resource/$resourceId'
    | '/session/$code'
    | '/admin/'
    | '/ai/'
    | '/admin/member/$memberId'
    | '/api/public/ai'
    | '/apply/growth/$token'
    | '/api/public/cron/notify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistants'
    | '/beginners'
    | '/chat'
    | '/courses'
    | '/dashboard'
    | '/enrollment-video'
    | '/executive'
    | '/founder'
    | '/leave'
    | '/notifications'
    | '/pay-mentorship'
    | '/profile'
    | '/reels'
    | '/resources'
    | '/search'
    | '/seats'
    | '/sessions'
    | '/team'
    | '/todo'
    | '/training'
    | '/training-room'
    | '/admin/login'
    | '/ai/$threadId'
    | '/api/ai'
    | '/course/$courseId'
    | '/join/$token'
    | '/lecture/$lectureId'
    | '/report/$token'
    | '/resource/$resourceId'
    | '/session/$code'
    | '/admin'
    | '/ai'
    | '/admin/member/$memberId'
    | '/api/public/ai'
    | '/apply/growth/$token'
    | '/api/public/cron/notify'
  id:
    | '__root__'
    | '/'
    | '/assistants'
    | '/beginners'
    | '/chat'
    | '/courses'
    | '/dashboard'
    | '/enrollment-video'
    | '/executive'
    | '/founder'
    | '/leave'
    | '/notifications'
    | '/pay-mentorship'
    | '/profile'
    | '/reels'
    | '/resources'
    | '/search'
    | '/seats'
    | '/sessions'
    | '/team'
    | '/todo'
    | '/training'
    | '/training-room'
    | '/admin/login'
    | '/ai/$threadId'
    | '/api/ai'
    | '/course/$courseId'
    | '/join/$token'
    | '/lecture/$lectureId'
    | '/report/$token'
    | '/resource/$resourceId'
    | '/session/$code'
    | '/admin/'
    | '/ai/'
    | '/admin/member/$memberId'
    | '/api/public/ai'
    | '/apply/growth/$token'
    | '/api/public/cron/notify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantsRoute: typeof AssistantsRoute
  BeginnersRoute: typeof BeginnersRoute
  ChatRoute: typeof ChatRoute
  CoursesRoute: typeof CoursesRoute
  DashboardRoute: typeof DashboardRoute
  EnrollmentVideoRoute: typeof EnrollmentVideoRoute
  ExecutiveRoute: typeof ExecutiveRoute
  FounderRoute: typeof FounderRoute
  LeaveRoute: typeof LeaveRoute
  NotificationsRoute: typeof NotificationsRoute
  PayMentorshipRoute: typeof PayMentorshipRoute
  ProfileRoute: typeof ProfileRoute
  ReelsRoute: typeof ReelsRoute
  ResourcesRoute: typeof ResourcesRoute
  SearchRoute: typeof SearchRoute
  SeatsRoute: typeof SeatsRoute
  SessionsRoute: typeof SessionsRoute
  TeamRoute: typeof TeamRoute
  TodoRoute: typeof TodoRoute
  TrainingRoute: typeof TrainingRoute
  TrainingRoomRoute: typeof TrainingRoomRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AiThreadIdRoute: typeof AiThreadIdRoute
  ApiAiRoute: typeof ApiAiRoute
  CourseCourseIdRoute: typeof CourseCourseIdRoute
  JoinTokenRoute: typeof JoinTokenRoute
  LectureLectureIdRoute: typeof LectureLectureIdRoute
  ReportTokenRoute: typeof ReportTokenRoute
  ResourceResourceIdRoute: typeof ResourceResourceIdRoute
  SessionCodeRoute: typeof SessionCodeRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AiIndexRoute: typeof AiIndexRoute
  AdminMemberMemberIdRoute: typeof AdminMemberMemberIdRoute
  ApiPublicAiRoute: typeof ApiPublicAiRoute
  ApplyGrowthTokenRoute: typeof ApplyGrowthTokenRoute
  ApiPublicCronNotifyRoute: typeof ApiPublicCronNotifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistants': {
      id: '/assistants'
      path: '/assistants'
      fullPath: '/assistants'
      preLoaderRoute: typeof AssistantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beginners': {
      id: '/beginners'
      path: '/beginners'
      fullPath: '/beginners'
      preLoaderRoute: typeof BeginnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enrollment-video': {
      id: '/enrollment-video'
      path: '/enrollment-video'
      fullPath: '/enrollment-video'
      preLoaderRoute: typeof EnrollmentVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive': {
      id: '/executive'
      path: '/executive'
      fullPath: '/executive'
      preLoaderRoute: typeof ExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave': {
      id: '/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof LeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay-mentorship': {
      id: '/pay-mentorship'
      path: '/pay-mentorship'
      fullPath: '/pay-mentorship'
      preLoaderRoute: typeof PayMentorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seats': {
      id: '/seats'
      path: '/seats'
      fullPath: '/seats'
      preLoaderRoute: typeof SeatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todo': {
      id: '/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof TodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-room': {
      id: '/training-room'
      path: '/training-room'
      fullPath: '/training-room'
      preLoaderRoute: typeof TrainingRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/': {
      id: '/ai/'
      path: '/ai'
      fullPath: '/ai/'
      preLoaderRoute: typeof AiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/$threadId': {
      id: '/ai/$threadId'
      path: '/ai/$threadId'
      fullPath: '/ai/$threadId'
      preLoaderRoute: typeof AiThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai': {
      id: '/api/ai'
      path: '/api/ai'
      fullPath: '/api/ai'
      preLoaderRoute: typeof ApiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId': {
      id: '/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/course/$courseId'
      preLoaderRoute: typeof CourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecture/$lectureId': {
      id: '/lecture/$lectureId'
      path: '/lecture/$lectureId'
      fullPath: '/lecture/$lectureId'
      preLoaderRoute: typeof LectureLectureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$token': {
      id: '/report/$token'
      path: '/report/$token'
      fullPath: '/report/$token'
      preLoaderRoute: typeof ReportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resource/$resourceId': {
      id: '/resource/$resourceId'
      path: '/resource/$resourceId'
      fullPath: '/resource/$resourceId'
      preLoaderRoute: typeof ResourceResourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$code': {
      id: '/session/$code'
      path: '/session/$code'
      fullPath: '/session/$code'
      preLoaderRoute: typeof SessionCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/member/$memberId': {
      id: '/admin/member/$memberId'
      path: '/admin/member/$memberId'
      fullPath: '/admin/member/$memberId'
      preLoaderRoute: typeof AdminMemberMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai': {
      id: '/api/public/ai'
      path: '/api/public/ai'
      fullPath: '/api/public/ai'
      preLoaderRoute: typeof ApiPublicAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/growth/$token': {
      id: '/apply/growth/$token'
      path: '/apply/growth/$token'
      fullPath: '/apply/growth/$token'
      preLoaderRoute: typeof ApplyGrowthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/notify': {
      id: '/api/public/cron/notify'
      path: '/api/public/cron/notify'
      fullPath: '/api/public/cron/notify'
      preLoaderRoute: typeof ApiPublicCronNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantsRoute: AssistantsRoute,
  BeginnersRoute: BeginnersRoute,
  ChatRoute: ChatRoute,
  CoursesRoute: CoursesRoute,
  DashboardRoute: DashboardRoute,
  EnrollmentVideoRoute: EnrollmentVideoRoute,
  ExecutiveRoute: ExecutiveRoute,
  FounderRoute: FounderRoute,
  LeaveRoute: LeaveRoute,
  NotificationsRoute: NotificationsRoute,
  PayMentorshipRoute: PayMentorshipRoute,
  ProfileRoute: ProfileRoute,
  ReelsRoute: ReelsRoute,
  ResourcesRoute: ResourcesRoute,
  SearchRoute: SearchRoute,
  SeatsRoute: SeatsRoute,
  SessionsRoute: SessionsRoute,
  TeamRoute: TeamRoute,
  TodoRoute: TodoRoute,
  TrainingRoute: TrainingRoute,
  TrainingRoomRoute: TrainingRoomRoute,
  AdminLoginRoute: AdminLoginRoute,
  AiThreadIdRoute: AiThreadIdRoute,
  ApiAiRoute: ApiAiRoute,
  CourseCourseIdRoute: CourseCourseIdRoute,
  JoinTokenRoute: JoinTokenRoute,
  LectureLectureIdRoute: LectureLectureIdRoute,
  ReportTokenRoute: ReportTokenRoute,
  ResourceResourceIdRoute: ResourceResourceIdRoute,
  SessionCodeRoute: SessionCodeRoute,
  AdminIndexRoute: AdminIndexRoute,
  AiIndexRoute: AiIndexRoute,
  AdminMemberMemberIdRoute: AdminMemberMemberIdRoute,
  ApiPublicAiRoute: ApiPublicAiRoute,
  ApplyGrowthTokenRoute: ApplyGrowthTokenRoute,
  ApiPublicCronNotifyRoute: ApiPublicCronNotifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
