REVOKE EXECUTE ON FUNCTION public.can_access_level_content(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.can_access_lecture(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.can_access_series(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.current_member_level() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.generate_member_id() FROM anon, public;
GRANT EXECUTE ON FUNCTION public.can_access_level_content(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.can_access_lecture(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.can_access_series(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.current_member_level() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.generate_member_id() TO service_role;